blog_deploy-without_weasyprint/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('about/', views.about, name='about'),    
    path('contact/', views.contact, name='conact'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, 
         name='post_share'),
    path('tag/<slug:tag_slug>/',
        views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

blog_deploy-without_weasyprint/blog_deploy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),    
    path('shop/', include('shop.urls', namespace='shop')),
    # path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, 
                          document_root=settings.STATIC_ROOT)

blog_deploy-without_weasyprint/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset()\
                          .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager. 
    tags = TaggableManager()                             
    
    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])        
    
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog_deploy-without_weasyprint/blog/forms.py
from django import forms
from . models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog_deploy-without_weasyprint/blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.shortcuts import render, get_object_or_404

from taggit.models import Tag

from . forms import CommentForm, EmailPostForm, SearchForm
from . models import Comment, Post

# Create your views here.
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags','-publish')[:4]


    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()    

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (
                f"{cd['name']} recommends you read " 
                f"{post.title}"
            )
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}\'s comments: {cd['comments']}"
            )
            send_mail(subject, message, 'info@mail.buffteks.net', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    """
    Postgres full-text search
    """
    search_form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']

            search_vector = SearchVector('title', weight='A') + \
                            SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query),
            ).filter(rank__gte=0.3).order_by('-rank')

    return render(request,
                  'blog/post/search.html',
                  {'search_form': search_form,
                   'query': query,
                   'results': results})


def about(request):
    return render(request, 'blog/about.html')


def contact(request):
    return render(request, 'blog/contact.html')

blog_deploy-without_weasyprint/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load crispy_forms_tags %}
{% block title %}{{ post.title }}{% endblock %}
{% block content %}

<!-- Post Content Column -->
<div class="col-lg-8">
    <!-- Title -->
    <h1 class="mt-4">{{ post.title }}</h1>

    <!-- Author -->
    <p class="lead">
        by <a href="#">{{ post.author }}</a>
    </p>

    <hr>
    <!-- Date/Time -->    
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>

    <hr>
    <!-- Preview Image -->
    <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">
    
    <hr>
    <!-- Post Content -->
    {% comment %} {{ post.body|linebreaks }} {% endcomment %}
    {{ post.body|markdown }}    
    <hr>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </p>
    {% empty %}
    There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} Comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}    
    <!-- Single Comment -->
    {% for comment in comments %}
        <div class="media mb-4">
            <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">    
            <div class="media-body">
                <h5 class="mt-0">Comment {{ forloop.counter }} by {{ comment.name }}</h5>
                {{ comment.created }}            
                {{ comment.body|linebreaks }}
            </div>        
        </div>
        {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    <!-- Comments Form -->
    <div class="card my-4">
        <div class="card-body">    
        {% if new_comment %}
            <h5 class="card-header">Your comment has been added.</h5>        
        {% else %}
            <h5 class="card-header">Leave a Comment:</h5>
            <form class="form-group" method="post">
                {{ comment_form | crispy }}
                {% csrf_token %}
                <button type="submit" class="btn btn-primary">Add Comment</button>
                {% comment %} <p><input type="submit" value="Add comment"></p> {% endcomment %}
                
            </form>
        {% endif %}  
        </div>        
    </div>    
</div>
{% endblock %}

blog_deploy-without_weasyprint/blog/templates/blog/post/latest_posts.html
<ul class="list-group">
    {% for post in latest_posts %}
        <li class="list-group-item list-group-item-action">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog_deploy-without_weasyprint/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}My Blog{% endblock %}
{% block content %}
<!-- Blog Entries Column -->
<div class="col-md-8">
    <h1 class="my-4">Craftiful                        
        <small>All things crafty to get you through this global pandemic! Please feel free to view around the shop's pages and contact us regarding any inquiries or questions! We're excited to have you here!</small>
    </h1>
    {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
    <!-- Blog Post -->
    <div class="card mb-4">
        <img class="card-img-top" src="https://i.ibb.co/MckSRnJ/ribbon-greetings-01-550-1.png" alt="Card image cap">
        <div class="card-body">
            <h2>
                <a class="card-title" href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h2>        
            <p class="tags">
                Tags:
                {% comment %} Tags: {{ post.tags.all|join:", " }} {% endcomment %}
                {% for tag in post.tags.all %}
                    <a href="{% url "blog:post_list_by_tag" tag.slug %}">
                        {{ tag.name }}
                    </a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
            </p>
            <p class="card-text">
                {% comment %} {{ post.body|truncatewords:30|linebreaks }}{% endcomment %}
                {{ post.body|markdown|truncatewords_html:30}}                
            </p>
            <a href="{{ post.get_absolute_url }}" class="btn btn-danger">Read More &rarr;</a>
        </div>
        <div class="card-footer text-muted">
            <p class="date">
                Published {{ post.publish }} by {{ post.author }}
            </p>
        </div>
    </div>
    {% endfor %}
    {% include "pagination.html" with page=posts %}      
</div>

{% endblock %}

blog_deploy-without_weasyprint/blog/templates/blog/post/most_commented.html
<ul class="list-group">
    {% for post in most_commented_posts %}
        <li class="list-group-item list-group-item-action">
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog_deploy-without_weasyprint/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% load crispy_forms_tags %}    
{% block title %}Search{% endblock %}
{% block content %}
<!-- Search Column -->
<div class="col-md-8">
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></h4>
            {{ post.body|markdown|truncatewords_html:5 }}
            {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        {% comment %} <p><a href="{% url "blog:post_search" %}">Search again</a></p> {% endcomment %}
    {% else %}
        <h1>Search for posts</h1>
        <div class="input-group">
            <form method="get">
                {{ search_form|crispy }}
                <input type="submit" value="Search">
            </form>                
        </div>            
    {% endif %}        
</div>
{% endblock %}

blog_deploy-without_weasyprint/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    <div class="col-lg-8">
    {% if sent %}
        <h1 class="mt-4">E-mail successfully sent}</h1>    
        <h1></h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1 class="mt-4">Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>        
    </div>
  {% endif %}
{% endblock %}