blog_deploy-without_weasyprint/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # post views
    path('', views.post_list, name='post_list'),
    path('about/', views.about, name='about'),    
    path('contact/', views.contact, name='conact'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail,
         name='post_detail'),
    path('<int:post_id>/share/',
         views.post_share, 
         name='post_share'),
    path('tag/<slug:tag_slug>/',
        views.post_list, name='post_list_by_tag'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

blog_deploy-without_weasyprint/blog_deploy/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cart/', include('cart.urls', namespace='cart')),
    path('payment/', include('payment.urls', namespace='payment')),
    path('orders/', include('orders.urls', namespace='orders')),    
    path('shop/', include('shop.urls', namespace='shop')),
    # path('', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
         name='django.contrib.sitemaps.views.sitemap'),
    path('', include('blog.urls', namespace='blog')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, 
                          document_root=settings.STATIC_ROOT)

blog_deploy-without_weasyprint/blog/models.py
from django.db import models
from django.urls import reverse
from django.utils import timezone
from django.contrib.auth.models import User

from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,
                     self).get_queryset()\
                          .filter(status='published')


class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )
    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                              on_delete=models.CASCADE,
                              related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,
                              choices=STATUS_CHOICES,
                              default='draft')
    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager. 
    tags = TaggableManager()                             
    
    class Meta:
        ordering = ('-publish',)

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day, self.slug])        
    
    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post,
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)
    
    class Meta:
        ordering = ('created',)
    
    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog_deploy-without_weasyprint/blog/forms.py
from django import forms
from . models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False,
                               widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')


class SearchForm(forms.Form):
    query = forms.CharField()

blog_deploy-without_weasyprint/blog/views.py
from django.core.mail import send_mail
from django.core.paginator import Paginator, EmptyPage,\
                                  PageNotAnInteger
from django.db.models import Count
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.shortcuts import render, get_object_or_404

from taggit.models import Tag

from . forms import CommentForm, EmailPostForm, SearchForm
from . models import Comment, Post

# Create your views here.
def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])

    paginator = Paginator(object_list, 3) # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request,
                  'blog/post/list.html',
                  {'page': page,
                   'posts': posts,
                   'tag': tag})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
                                   status='published',
                                   publish__year=year,
                                   publish__month=month,
                                   publish__day=day)
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids)\
                        .exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags'))\
                                 .order_by('-same_tags','-publish')[:4]


    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()    

    return render(request,
                  'blog/post/detail.html',
                  {'post': post,
                   'comments': comments,
                   'new_comment': new_comment,
                   'comment_form': comment_form,
                   'similar_posts': similar_posts})


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = (
                f"{cd['name']} recommends you read " 
                f"{post.title}"
            )
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}\'s comments: {cd['comments']}"
            )
            send_mail(subject, message, 'info@mail.buffteks.net', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post,
                                                    'form': form,
                                                    'sent': sent})


def post_search(request):
    """
    Postgres full-text search
    """
    search_form = SearchForm()
    query = None
    results = []
    if 'query' in request.GET:
        search_form = SearchForm(request.GET)
        if search_form.is_valid():
            query = search_form.cleaned_data['query']

            search_vector = SearchVector('title', weight='A') + \
                            SearchVector('body', weight='B')
            search_query = SearchQuery(query)
            results = Post.published.annotate(
                search=search_vector,
                rank=SearchRank(search_vector, search_query),
            ).filter(rank__gte=0.3).order_by('-rank')

    return render(request,
                  'blog/post/search.html',
                  {'search_form': search_form,
                   'query': query,
                   'results': results})


def about(request):
    return render(request, 'blog/about.html')


def contact(request):
    return render(request, 'blog/contact.html')

blog_deploy-without_weasyprint/blog/templates/blog/about.html
{% extends "blog/base.html" %}
{% block title %}About My Blog{% endblock %}
{% block content %}
<div class="col-md-8">
    <h1>If you’re interested in learning a new skill, while you’re stuck inside during this global pandemic. These
craft kits for adults and kids make learning a new hobby as easy and convenient as possible.
Whether you want to crochet a beanie or bake your own perfect sourdough bread, taking up a new
hobby is a satisfying way to de-stress and practice self-care.
To help, we’ve rounded up the best adult and kids’ craft kits and supplies to help you start creating right
away.</h1>
</div>
{% endblock content %}

blog_deploy-without_weasyprint/blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" 
          href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" 
          integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" 
          crossorigin="anonymous">
    {% comment %} <link href="vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet"> {% endcomment %}

    <!-- Custom styles for this template -->
    {% comment %} <link href="css/blog-home.css" rel="stylesheet"> {% endcomment %}

    <link href="{% static "css/blog.css" %}" rel="stylesheet">
    {% comment %} Favicon built with: https://favicon.io/favicon-generator/ {% endcomment %}
    <link rel="shortcut icon" type="image/ico" href="{% static 'favicon.ico' %}"/>
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon-16x16.png' %}">
    <link rel="manifest" href="{% static "site.webmanifest" %}"> 
</head>
<body class="d-flex flex-column">
    {% include "blog/navigation.html" %}
    <div id="page-content">
        <!-- Page Content -->
        <div class="container">
            <div class="row">
                {% block content %}
                {% endblock content %}
            {% include 'blog/sidebar.html'%}
            </div>
        </div>
    </div>
  {% include "blog/footer.html" %}

    <!-- jQuery and JS bundle w/ Popper.js -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" 
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" 
            crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" 
            integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" 
            crossorigin="anonymous">
    </script>  
</body>
</html>

blog_deploy-without_weasyprint/blog/templates/blog/contact.html
{% extends "blog/base.html" %}
{% block title %}Contact me{% endblock %}
{% block content %}
<div class="col-md-8">
    <h1>Have questions about our products? Let's talk about how we can help you achieve your crafting/knitting goals and send you the right kits to get you on top of all your crafts! Please e-mail us at Craftiful@gmail.com!</h1>
</div>
{% endblock content %}

blog_deploy-without_weasyprint/blog/templates/blog/footer.html
  <!-- Footer -->
  <footer id="sticky-footer" class="py-5 bg-primary">
    <div class="container">
      <p class="m-0 text-center text-white">
        Copyright &copy; Craftiful Products 
        <script>document.write(new Date().getFullYear())</script>
      </p>
    </div>
  </footer>

blog_deploy-without_weasyprint/blog/templates/blog/navigation.html
<!-- Navigation -->
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
    <div class="container">
        <a class="navbar-brand" href="/">Craftiful</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">Announcements
                        <span class="sr-only">(current)</span>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/about">What We're About</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/contact">Contact Our Team</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="/shop">Shops and Products</a>
                </li>                
                <li class="nav-item">
                    <a class="nav-link" href="/search">Search</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

blog_deploy-without_weasyprint/blog/templates/blog/sidebar.html
{% load blog_tags %}
<!-- Sidebar Widgets Column -->
<div class="col-md-4">

    <!-- Side Widget -->
    <div class="card my-4">
        <h5 class="card-header">Blog Features</h5>
        <div class="card-body">
            <p>
                This is my blog. I've written {% total_posts %} posts so far.
            </p>
            <h5>Latest posts</h5>
            {% show_latest_posts 3 %}
            <h5>Most commented posts</h5>
            {% show_most_commented_posts 3 %}
            <p>
            <a href="{% url "blog:post_feed" %}">Subscribe to my RSS feed</a>
            </p>            
        </div>
    </div>

    <!-- Categories Widget -->
    <div class="card my-4">
        <h5 class="card-header">Categories</h5>
        <div class="card-body">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="#">Knitting</a>
                        </li>
                        <li>
                            <a href="#">Crafts</a>
                        </li>
                        <li>
                            <a href="#">DIY Kits</a>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <ul class="list-unstyled mb-0">
                        <li>
                            <a href="#">Tutorials</a>
                        </li>
                        <li>
                            <a href="#">Hats and Clothing</a>
                        </li>
                        <li>
                            <a href="#">Seasonal Products</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</div>